version: 0.1
log:
  accesslog:
    disabled: true
  level: warn
http:
  addr: :5000
  secret: SECRET
redis:
  addr: redisdb:6379
storage:
  filesystem:
    rootdirectory: /var/lib/registry
  delete:
    enabled: true
notifications:
  events:
    includereferences: true
  endpoints:
    - name: alistener
      disabled: false
      url: http://host.docker.internal:3030/event
      timeout: 1s
      threshold: 10
      backoff: 1s
      ignoredmediatypes:
        - application/octet-stream
      ignore:
        mediatypes:
           - application/octet-stream
        # actions:
        #    - pull
